name: gsplat
channels:
  - pytorch
  - defaults
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python=3.10
  - cuda-version==11.8 
  - cudnn==8.9.7.29
  - cuda-toolkit=11.8
  - pytorch=2.1.0
  - pip:
    - numpy==1.26.4
variables:
   CUDA_PATH: ""